# Generated by Django 5.2.11 on 2026-02-21 17:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_meal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snacks', 'Snacks')], default='breakfast', max_length=20),
        ),
        migrations.AddField(
            model_name='meal',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
